import React, { useRef } from 'react';
import LandingNavigation from './LandingNavigation';
import immutableledger from '../image/immutableledger.png';
import decentralization from '../image/decentralization.png';
import dataintegrity from '../image/dataintegrity.png';
import smartcontract from '../image/smartcontract.png';
import transparency from '../image/transparency.png';
import traceability from '../image/traceability.png';
import AttendPro from '../image/AttendPro.png';
import signin from '../image/signin.png';
import mobileImage from '../image/mobile.png';
import pema from "../image/pemayeshi.png";
import dema from "../image/dema.png";
import Footer from '../Component/Student/Footer';

const blockchainFeatures = [
    {
        title: "Immutable Ledger",
        description: "Once attendance records are recorded on the blockchain, they cannot be altered or tampered ensuring data integrity.",
        image: immutableledger,
    },
    {
        title: "Decentralization",
        description: "Remove the need for a central authority to manage attendance records, enhancing security.",
        image: decentralization,
    },
    {
        title: "Data Integrity",
        description: "Ensures data integrity by linking attendance records in blocks.",
        image: dataintegrity,
    },
    {
        title: "Smart Contract",
        description: "Self-executing contracts with the terms of the agreement directly written into code.",
        image: smartcontract,
    },
    {
        title: "Transparency",
        description: "Allow only authorized parties to access and verify attendance records promoting accountability.",
        image: transparency,
    },
    {
        title: "Traceability",
        description: "Every transaction on a blockchain is recorded chronologically and is traceable back to its origin.",
        image: traceability,
    },
];

const FeatureCard = ({ title, description, image }) => (
    <div className="w-full md:w-1/2 lg:w-1/3 p-4">
        <div className="bg-white shadow-lg rounded-lg p-6 text-center" style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
            <img src={image} alt={title} className="h-full w-full mx-auto mb-4" style={{ height: "10rem", width: "12rem" }} />
            <h5 className="text-lg font-bold mb-2">{title}</h5>
            <p className="text-gray-600" style={{ height: "6rem", width: "100%" }} >{description}</p>
        </div>
    </div>
);

const howItWorks = [
    {
        title: "Sign In",
        description: "Sign in with your Student ID",
        image: signin,
    },
    {
        title: "Scan QR Code",
        description: "Scan the QR code generated by your lecturer",
        image: mobileImage,
    },
    {
        title: "Store Your Attendance",
        description: "Store your attendance on Blockchain",
        image: transparency,
    },
];
const HowItWorkCard = ({ title, description, image }) => (
    <div className="w-full md:w-1/2 lg:w-1/3 p-4">
        <div className="bg-white shadow-lg rounded-lg p-6 text-center" style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
            <img src={image} alt={title} className="h-full w-full mx-auto mb-4" style={{ height: "8rem", width: "10rem" }} />
            <h5 className="text-lg font-bold mb-2">{title}</h5>
            <p className="text-gray-600" style={{ height: "4rem", width: "100%" }} >{description}</p>
        </div>
    </div>
);

const teamSection = [
    {
        title: "Chencho Dema",
        description: "Scrum Master & UI UX developer",
        description1: "Email: 12210045.gcit@rub.edu.bt",
        description2: "Contact: 17893248",
        image: dema,
    },
    {
        title: "Pema Yeshi Tshering",
        description: "FrontEnd & BackEnd Developer",
        description1: "Email: 12210075.gcit@rub.edu.bt",
        description2: "Contact: 17893248",
        image: pema,
    },
    {
        title: "Sonam Tshering",
        description: "FrontEnd & BackEnd Developer",
        description1: "Email: 12210033.gcit@rub.edu.bt",
        description2: "Contact: 17893248",
        image: dema,
    },
    {
        title: "Jampel Dorji",
        description: "UI UX Designer",
        description1: "Email: 12200047.gcit@rub.edu.bt",
        description2: "Contact: 17893248",
        image: pema,
    },
];

const TeamSectionCard = ({ title, description, description1, description2, image }) => (
    <div className="w-full md:w-1/2 lg:w-1/3 p-4">
        <div className="bg-white rounded-lg text-center" style={{ flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
            <img src={image} alt={title} className="h-full w-full mx-auto mb-4" style={{ height: "20rem", width: "18rem" }} />
            <h5 className="text-lg font-bold mb-2">{title}</h5>
            <p className="text-gray-600" style={{ height: "6rem", width: "100%" }} >
                {description} <br />
                {description1} <br />
                {description2}
            </p>
        </div>
    </div>
);

const LandingPage = () => {
    const featuresRef = useRef(null);
    const aboutRef = useRef(null);
    const howItWorksRef = useRef(null);
    const contactRef = useRef(null);

    return (
        <div className="overflow-y-scroll h-screen">
            <LandingNavigation
                featuresRef={featuresRef}
                aboutRef={aboutRef}
                howItWorksRef={howItWorksRef}
                contactRef={contactRef}
            />
            <div className="mb-4">
                <div className="container mx-auto px-4 py-8 mt-5">
                    <div className="flex flex-col md:flex-row items-center mt-8">
                        <div className="w-full md:w-1/2 p-4">
                            <h2 className="text-lg font-semibold text-gray-800">Experience the future of attendance management</h2>
                            <h1 className="text-4xl font-bold text-gray-900 mt-4">
                                Transform The Way You{" "}
                                <span
                                    style={{
                                        background: "linear-gradient(to right, #8EA5FE, #BEB3FD, #90D1FF)",
                                        WebkitBackgroundClip: "text",

                                        WebkitTextFillColor: "transparent"
                                    }}
                                >
                                    Track Attendance
                                </span>
                            </h1>
                            <p className="text-gray-600 mt-4">Say goodbye to paper records and hello to seamless digital attendance management using Blockchain Technology.</p>
                        </div>
                        <div className="w-full md:w-1/2 p-4">
                            <img src={mobileImage} alt="Mobile" className="w-full h-auto mb-5 mt-5" />
                        </div>
                    </div>
                    <div className="text-center" ref={featuresRef}>
                        <h3 className="text-3xl font-bold text-gray-800">Amazing Features of Blockchain Technology</h3>
                        <p className="text-gray-600 mt-4 font-bold">Discover some of the incredible Blockchain Technology elements that "AttendPro" </p>
                        <p className="text-gray-600 mt-4 font-bold">leverages to enhance student attendance tracking.</p>
                        <div className="p-4 border-2 border-gray-200 border rounded-lg dark:border-gray-700 mt-5 mb-5">
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-8">
                                {blockchainFeatures.map((feature, index) => (
                                    <FeatureCard key={index} {...feature} />
                                ))}
                            </div>
                        </div>
                    </div>
                    <div className="mt-16 flex flex-col md:flex-row items-center" ref={aboutRef}>
                        <div className="flex w-full md:w-1/2 p-4 text-center items-center justify-center">
                            <img src={AttendPro} alt="AttendPro" className="mb-5" style={{ height: "33rem" }} />
                        </div>
                        <div className="w-full md:w-1/2 p-4">
                            <h2 className="text-2xl font-bold" style={{ color: '#6574cd' }}>Track Student Attendance</h2>
                            <h1 className="text-4xl font-bold text-gray-900 mt-4">Maintain student attendance records on the blockchain</h1>
                            <p className="text-gray-600 mt-4">
                                Using state-of-the-art blockchain technology, AttendPro is a revolutionary student attendance management system that is revolutionizing the tracking of attendance in educational settings. Our goal is to improve efficiency, accountability, and transparency by streamlining the attendance process for instructors and pupils.
                                AttendPro guarantees safe and impenetrable attendance recording by utilizing blockchain technology, geofencing capabilities, and dynamic QR code generation. This eliminates the need for manual paperwork and lessens administrative burden.
                                Our enthusiastic development team is committed to delivering an excellent, user-friendly solution that gives instructors the ability to easily manage attendance while giving students a simple and dependable way to monitor their attendance in class.
                                By adopting AttendPro, educational establishments can welcome the future of attendance management and cultivate an environment where students are engaged and accountable.
                            </p>
                        </div>
                    </div>
                    <div className="w-full md:w-1/2 p-4">
                        <h2 className="text-2xl text-gray-800 text-center font-bold" ref={howItWorksRef}>How It Works</h2>
                        <div className="p-4 dark:border-gray-700 mt-5 mb-5">
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-8">
                                {howItWorks.map((step, index) => (
                                    <HowItWorkCard key={index} {...step} />
                                ))}
                            </div>
                        </div>
                    </div>
                    <div className="w-full md:w-1/2 p-4">
                        <h2 className="text-2xl font-bold text-gray-800 p-4 text-center" ref={contactRef}>Team</h2>
                        <p className="text-gray-600 mt-4 text-center mb-8">Meet the brilliant minds behind "AttendPro"</p>
                        <div className="p-4 border-2 border-gray-200 border rounded-lg dark:border-gray-700 mt-5 mb-5">
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 mt-8">
                                {teamSection.map((member, index) => (
                                    <TeamSectionCard key={index} {...member} />
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default LandingPage;
